#!/bin/sh

bspc config border_width        1
bspc config window_gap          10

# for monitor in $(bspc query -M); do
    # bspc monitor $monitor -d 1,2,3,4,5,6,7,8,9
# done

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config top_padding 60
bspc config right_padding 20
bspc config left_padding 20
bspc config bottom_padding 20

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a '*:keepassx' state=floating
bspc rule -a Chromium-browser desktop=^1
bspc rule -a Skype pseudo_tiled=on
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Skype pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=off
bspc rule -a gcolor2 floating=true center=true
bspc rule -a sxiv floating=true center=true
bspc rule -a xfontsel floating=true center=true
bspc rule -a lxappearance floating=true center=true
bspc rule -a gimp floating=true
bspc rule -a pavucontrol desktop=X follow=true floating=true center=true

# compton -b &
SHELL=/bin/bash polybar top -r &
