#!/bin/sh
#		  _                                                    __ _
#		 | |__  ___ _ ____      ___ __ ___     ___ ___  _ __  / _(_) __ _
#		 | '_ \/ __| '_ \ \ /\ / / '_ ` _ \   / __/ _ \| '_ \| |_| |/ _` |
#		 | |_) \__ \ |_) \ V  V /| | | | | | | (_| (_) | | | |  _| | (_| |
#		 |_.__/|___/ .__/ \_/\_/ |_| |_| |_|  \___\___/|_| |_|_| |_|\__, |
#		           |_|                                              |___/

bspc config border_width 3
bspc config window_gap   10


if [[ $(hostname) == 'skylake' ]]; then
    xrandr --output HDMI1 --primary --left-of eDP1
    bspc monitor HDMI1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9 0
	bspc config -m eDP1 top_padding 8
	bspc config -m eDP1 top_padding    0
	bspc config -m eDP1 right_padding  0
	bspc config -m eDP1 left_padding   0
	bspc config -m eDP1 bottom_padding 0
	bspc config -m eDP1 border_width   0
	bspc config -m eDP1 window_gap     0
    export MONITOR=HDMI1 && SHELL=/bin/bash polybar -r top-bspwm-work &
fi

if [[ $(hostname) == 'arch' ]]; then
    xrandr --output DVI-I-1 --primary --left-of VGA-0
    bspc monitor DVI-I-1 -d 1 2 3 4 5
    bspc monitor VGA-0 -d 6 7 8 9 0
	bspc config -m VGA-0 top_padding    0
	bspc config -m VGA-0 right_padding  0
	bspc config -m VGA-0 left_padding   0
	bspc config -m VGA-0 bottom_padding 0
	bspc config -m VGA-0 border_width   0
	bspc config -m VGA-0 window_gap     0
    export MONITOR=DVI-I-1 && SHELL=/bin/bash polybar -r top-bspwm &
fi

# some extra top space for bar
bspc config top_padding    45
bspc config right_padding  8
bspc config left_padding   8
bspc config bottom_padding 8

# Visual options
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config click_to_focus	      true
bspc config split_ratio           0.50
bspc config focused_border_color  "#87AFAF"

# Rules
bspc rule -a '*:keepassx2:*' state=tiled split_dir=south split_ratio=0.66 focus=on
bspc rule -a SpeedCrunch     state=tiled split_dir=south split_ratio=0.66 focus=on
bspc rule -a Gvim            state=tiled split_dir=north split_ratio=0.1  focus=on
bspc rule -a '*:tilda:*'     state=tiled split_dir=north split_ratio=0.3  focus=on

bspc rule -a Conky  sticky=on manage=off lower=on
bspc rule -a astime sticky=on

bspc rule -a '*:Profile error occurred:*' state=floating focus=on
bspc rule -a '*:KeePassHttp: Confirm Access:*' state=floating focus=on
bspc rule -a '*:zathura:*' state=tiled

bspc rule -a Firefox	      desktop=1 focus=on
bspc rule -a Thunderbird      desktop=3
bspc rule -a Hexchat	      desktop=5
bspc rule -a Vlc              desktop=4

# pseudo tiled rules
bspc rule -a Thunar           pseudo_tiled=on focus=on
bspc rule -a Skype            pseudo_tiled=on
bspc rule -a File-roller      pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on

# floating rules
bspc rule -a feh             state=floating manage=off
bspc rule -a gcolor2         state=floating center=true focus=on
bspc rule -a sxiv            state=floating center=true
bspc rule -a xfontsel        state=floating center=true focus=on
bspc rule -a lxappearance    state=floating center=true focus=on
bspc rule -a gimp            state=floating

bspc rule -a Meld state=fullscreen center=true focus=on
bspc rule -a Slack desktop=1 state=fullscreen center=true focus=on
bspc rule -a pavucontrol desktop=X follow=true state=floating center=true

# hile true; do MONITOR=VGA-1 && SHELL=/bin/bash polybar -r top-bspwm; sleep5; done &
# while true; do MONITOR=VGA-1 && SHELL=/bin/bash polybar -r top-bspwm; sleep5; done &
nm-applet &

xdotool search --onlyvisible --name tilda windowfocus
